### ISSUE TITLE
Integrate Timex Ecto

### ISSUE THREAD

**Issue by rrrene** [rrrene/elixirstatus-web#20]
From what I have read and understood, we want to use Timex for all time-related stuff in our little project. So we should also use this: https://github.com/bitwalker/timex_ecto

@bitwalker could you give some input on this: Is it really "just" adding `Timex.Ecto.DateTime` to the schemas and model in Phoenix?

**Comment by bitwalker** [comment]
@rrrene Yep! I created some [nicer docs here](http://timex.readme.io/docs/using-with-ecto) that talk about using it in depth. The only real caveat is if you choose to use the `Timex.Ecto.DateTimeWithTimezone` type, which requires you to run a `CREATE TYPE` command in postgres in order to use it (I just realized I need to cover that in the Timex docs as well, as it's only detailed in the `timex_ecto` readme). That type is only really important when you *need* to store timezone information with the datetime though, and since I doubt that's really relevant for this application, `Timex.Ecto.DateTime` should be all you need, as it stores the datetime as UTC (it will be localized within postgres due to the way postgres works, but when read it will be treated as UTC).

**Comment by bitwalker** [comment]
Ah, I just saw that you are using MySQL for the time being, so be aware of the fact that `Timex.Ecto.DateTimeWithTimezone` is not supported (at least until MySQL supports user-defined types). If you need to persist timezone information, you can work around it by using `Timex.Ecto.DateTime` and then the timezone name as a string column, and then just provide a function (effectively a calculated property) which shifts the datetime value to the timezone stored in that column. As I mentioned above though, I don't think you'll need to use anything other than UTC on the backend anyway.

**Comment by rrrene** [comment]
Thanks for the pointers. It was really straight-forward! :+1:
